### ISSUE TITLE
Node onCreate method not call when option "dot't keep activities" is on

### ISSUE THREAD

**Issue by UDenis** [badoo/RIBs#302] opened 2021-05-14 09:02 UTC
I'm testing our application with option "dot't keep activities" is on.
Steps for reproduce bug:
1) open some rib (Rib A),
2) open some second rib (Rib B) using backstack.push
3) move app to backgroud
4) move app to foreground
5) press back button

<img width="1376" alt="Снимок экрана 2021-05-14 в 13 55 28" src="https://user-images.githubusercontent.com/2445115/118247628-0ec38000-b4ac-11eb-9fc6-d0a9434aa94e.png">

com.github.badoo.RIBs:rib-base:0.26.2

**Comment by zsoltk** [comment] 2021-05-15 20:17
Hi @UDenis, thanks for the report. I could reproduce and after investigating it I know where the issue is coming from. Fix coming soon.

**Comment by zsoltk** [comment] 2021-05-26 21:44
Will be released with next version 0.27 next week.

**Closed** 2021-05-26 21:43 UTC
Labels: bug
